### ISSUE TITLE
Crashes on inputs with numel == 0

### ISSUE THREAD

**Issue by jhultman** [rusty1s/pytorch_scatter#39] opened 2019-04-11 18:09 UTC
Hi, thanks so much for providing this package--it's very useful. I am running `torch 1.0.1.post2` on Ubuntu 16.04 with NVIDIA Quadro P4000 and with `torch_scatter` installed recently via pip. Please see my minimum working example below which demonstrates what I feel is a bug. Notice that `num_vals == 0`. 

```
import torch
from torch_scatter import scatter_mean, scatter_max

num_vals = 0
m, n, k = 4, 5, 6

src = torch.zeros((m, n, num_vals)).cuda()
index = torch.zeros((m, n, num_vals)).long().cuda()
kwargs = dict(src=src, index=index, dim=2, dim_size=k)

for _ in range(2):
    out = scatter_mean(**kwargs)
    
for _ in range(2):
    out, argmax = scatter_max(**kwargs)
```

- `scatter_mean`, which I understand is mostly just a wrapper for `torch.scatter_add_`, handles the `tensor.numel() == 0` case gracefully.

- But `scatter_max` fails with `RuntimeError: cuda runtime error (9) : invalid configuration argument at /.../aten/src/THC/generic/THCTensorMath.cu:14`.

I guess the culprit is `#define BLOCKS(N) (N + THREADS - 1) / THREADS` in `scatter_kernel.cu` which doesn't work so well for `N == 0`.

**Comment by rusty1s** [comment] 2019-04-12 09:08
I can not reproduce your error. `N` should be of the size `src.numel()`, so there shouldn't be a problem.

**Comment by jhultman** [comment] 2019-04-12 15:10
I am surprised it cannot be reproduced. Yes, N is `src.numel()` which in my example above is 0.
Here's a simpler example with `scatter_mul` which I think you will be able to reproduce:

```
import torch
import torch_scatter

def demo(op):
    src = torch.tensor([[], []], dtype=torch.float32, device='cuda')
    index = torch.tensor([[], []], dtype=torch.long, device='cuda')
    out = torch.full((2, 5), 0, dtype=torch.float32, device='cuda')
    expected = out.clone()
    out = op(src=src, index=index, dim=1, out=out)
    torch.testing.assert_allclose(out, expected)

demo(torch_scatter.scatter_add)
">> ...Passes"
demo(torch_scatter.scatter_mul)
">> ...Throws"
```

If you want a failing test case, here's one I've tested:

```
tests = [{
    'name': 'add',
    'src': [[], []],
    'index': [[], []],
    'dim': -1,
    'fill_value': 0,
    'expected': [[], []],
}, {
    'name': 'mul',
    'src': [[], []],
    'index': [[], []],
    'dim': -1,
    'fill_value': 0,
    'expected': [[], []],
}]
```

The first one passes and the second throws RunTimeError. Let me know if you think I am misunderstanding expected behavior.

**Comment by rusty1s** [comment] 2019-04-12 15:13
Still cannot reproduce. Mmmh, I am not sure what may causes the error on your end. In the easiest case, we could simple check if `size(dim)` is greater than `0`.

**Comment by jhultman** [comment] 2019-04-12 15:29
I guess it could be architecture-specific. I just tried a simple script where I launch a CUDA kernel with 0 blocks on my Quadro card and I get the same `CUDA error: invalid configuration argument`. Yes, a size check in Python avoids the the problem for me at the cost of cluttering up the codebase a little bit.

**Comment by rusty1s** [comment] 2019-04-12 15:38
Fixed in master :)

**Comment by jhultman** [comment] 2019-04-12 15:39
Thanks!

**Comment by jhultman** [comment] 2019-04-12 16:25
Hate to reopen this but I think there is a related problem with line 15 in `utils/gen.py`. This one you definitely will be able to reproduce since it has nothing to do with CUDA.

`index.max().item()` throws error for `index.numel() == 0` since it tries to take max of an empty sequence. I guess we need something ugly like:

```
def _get_dim_size(index, dim_size):
    if dim_size is not None:
        return dim_size
    if index.numel() > 0:
        return index.max() + 1
    return 0
```

**Comment by rusty1s** [comment] 2019-04-12 16:49
Mh, shouldn't it crash when `index` has no values and `out` is not provided?

**Comment by jhultman** [comment] 2019-04-12 18:01
This use-case is probably of little interest anyway but for consistency I think it would make sense for `out.shape[dim] == 0` if `dim_size == None`, `index.numel() == 0`, and `out == None`. The API says "If dim_size is not given, a minimal sized output tensor is returned." I think you can make a good argument that minimal should mean `dim_size == 0` if there are no elements to scatter. Some people might want to use this package for "variable-size input -> variable-size output" computation by letting both  `index.shape` and `out.shape` be determined at run-time. Their programs will crash if they cannot guarantee `index.numel() > 0`.

**Comment by rusty1s** [comment] 2019-04-13 06:05
Great! Fixed in master :)

**Closed by rusty1s** 2019-04-13 06:05 UTC
