### ISSUE TITLE
FileNotFoundError: _scatter_cuda.pyd (or one of its dependencies)

### ISSUE THREAD

**Issue by Cbezz** [rusty1s/pytorch_scatter#295] opened 2022-05-14 18:39 UTC
Hi,

I've installed torch-scatter 2.0.9 using pip (on windows) and I'm running torch1.11 (torchvision 0.12.0) with cuda 11.3.
When I try and run code from another repository where pytorch_scatter is a dependency I'm getting the error in the thread title.

This is the other repository just in case anyone is curious: https://github.com/xmlyqing00/AFB-URR

Is there something I've done wrong, or not done, has anyone else had this issue?
Thanks

**Comment by rusty1s** [comment] 2022-05-14 21:15
Duplicate of https://github.com/rusty1s/pytorch_scatter/issues/296

**Closed by rusty1s** 2022-05-14 21:15 UTC
